#!/bin/bash

# Even with the nop sled, I kept getting segmentation faults when running ./stack5 out of debugger.
# It ultimately was caused by performing the invocation like
# ./stack5
# instead of
# /opt/protostar/bin/stack5
# which is the way gdb loads the argv[0] (the program name)
# This caused the environment to be different and thus the exploit worked in gdb but not out of it

# Also, the cat trick is used here again to keep the shell open

(python /tmp/exploit.py && cat) | /opt/protostar/bin/stack5
